/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary) / 0.05)',
          100: 'rgb(var(--color-primary) / 0.1)',
          200: 'rgb(var(--color-primary) / 0.2)',
          300: 'rgb(var(--color-primary) / 0.3)',
          400: 'rgb(var(--color-primary) / 0.4)',
          500: 'rgb(var(--color-primary) / 0.5)',
          600: 'rgb(var(--color-primary) / 0.6)',
          700: 'rgb(var(--color-primary) / 0.7)',
          800: 'rgb(var(--color-primary) / 0.8)',
          900: 'rgb(var(--color-primary) / 0.9)',
          950: 'rgb(var(--color-primary) / 0.95)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary) / 0.05)',
          100: 'rgb(var(--color-secondary) / 0.1)',
          200: 'rgb(var(--color-secondary) / 0.2)',
          300: 'rgb(var(--color-secondary) / 0.3)',
          400: 'rgb(var(--color-secondary) / 0.4)',
          500: 'rgb(var(--color-secondary) / 0.5)',
          600: 'rgb(var(--color-secondary) / 0.6)',
          700: 'rgb(var(--color-secondary) / 0.7)',
          800: 'rgb(var(--color-secondary) / 0.8)',
          900: 'rgb(var(--color-secondary) / 0.9)',
          950: 'rgb(var(--color-secondary) / 0.95)',
        },
        accent: {
          50: 'rgb(var(--color-accent) / 0.05)',
          100: 'rgb(var(--color-accent) / 0.1)',
          200: 'rgb(var(--color-accent) / 0.2)',
          300: 'rgb(var(--color-accent) / 0.3)',
          400: 'rgb(var(--color-accent) / 0.4)',
          500: 'rgb(var(--color-accent) / 0.5)',
          600: 'rgb(var(--color-accent) / 0.6)',
          700: 'rgb(var(--color-accent) / 0.7)',
          800: 'rgb(var(--color-accent) / 0.8)',
          900: 'rgb(var(--color-accent) / 0.9)',
          950: 'rgb(var(--color-accent) / 0.95)',
        },
        success: {
          50: 'rgb(var(--color-success) / 0.05)',
          100: 'rgb(var(--color-success) / 0.1)',
          200: 'rgb(var(--color-success) / 0.2)',
          300: 'rgb(var(--color-success) / 0.3)',
          400: 'rgb(var(--color-success) / 0.4)',
          500: 'rgb(var(--color-success) / 0.5)',
          600: 'rgb(var(--color-success) / 0.6)',
          700: 'rgb(var(--color-success) / 0.7)',
          800: 'rgb(var(--color-success) / 0.8)',
          900: 'rgb(var(--color-success) / 0.9)',
          950: 'rgb(var(--color-success) / 0.95)',
        },
        warning: {
          50: 'rgb(var(--color-warning) / 0.05)',
          100: 'rgb(var(--color-warning) / 0.1)',
          200: 'rgb(var(--color-warning) / 0.2)',
          300: 'rgb(var(--color-warning) / 0.3)',
          400: 'rgb(var(--color-warning) / 0.4)',
          500: 'rgb(var(--color-warning) / 0.5)',
          600: 'rgb(var(--color-warning) / 0.6)',
          700: 'rgb(var(--color-warning) / 0.7)',
          800: 'rgb(var(--color-warning) / 0.8)',
          900: 'rgb(var(--color-warning) / 0.9)',
          950: 'rgb(var(--color-warning) / 0.95)',
        },
        error: {
          50: 'rgb(var(--color-error) / 0.05)',
          100: 'rgb(var(--color-error) / 0.1)',
          200: 'rgb(var(--color-error) / 0.2)',
          300: 'rgb(var(--color-error) / 0.3)',
          400: 'rgb(var(--color-error) / 0.4)',
          500: 'rgb(var(--color-error) / 0.5)',
          600: 'rgb(var(--color-error) / 0.6)',
          700: 'rgb(var(--color-error) / 0.7)',
          800: 'rgb(var(--color-error) / 0.8)',
          900: 'rgb(var(--color-error) / 0.9)',
          950: 'rgb(var(--color-error) / 0.95)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      spacing: {
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in': 'slideInRight 0.3s ease-out',
        'spin': 'spin 1s linear infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      boxShadow: {
        'inner-sm': 'inset 0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        solid: '0 0 0 2px currentColor',
        'solid-focus': '0 0 0 3px currentColor',
      },
    },
  },
  plugins: [],
};